# Generated by Django 3.2.19 on 2023-06-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0003_auto_20230602_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadcontratoaumentos',
            name='diferencia_fianza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia de fianza'),
        ),
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='aumentos_fianza_actualizada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fianza actualizada'),
        ),
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='aumentos_indice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Índice de aumento'),
        ),
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='aumentos_mensual_actualizado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mensual actualizado'),
        ),
    ]
