# Generated by Django 3.2.19 on 2023-06-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0005_auto_20230610_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadeducciones',
            options={'ordering': ['fk_Propiedadeducciones_Propiedades'], 'verbose_name': 'Deducciones de la Propiedad'},
        ),
        migrations.RemoveField(
            model_name='propiedadeducciones',
            name='servicios_pago_inquilinos',
        ),
        migrations.AddField(
            model_name='propiedadeducciones',
            name='servicios_pago_propiedad',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='N', max_length=2, verbose_name='Corresponde a la propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedadcontratogarante',
            name='garante',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='N', max_length=25, verbose_name='Garante'),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='cocina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Cocina'),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='terraza',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Terraza'),
        ),
        migrations.AlterField(
            model_name='tipodeduccion',
            name='tipo_deduccion_descripcion',
            field=models.CharField(choices=[('RSU', 'RSU (S)'), ('IBI', 'IBI (G)'), ('Comunidad', 'Comunidad (G)'), ('Seguro del hogar', 'Seguro del hogar (G)'), ('Luz', 'Luz (S)'), ('Agua', 'Agua (S)'), ('Gas', 'Gas (S)'), ('Internet', 'Internet (S)'), ('Electricista', 'Electricista (G)'), ('Calefacción', 'Calefacción (G)'), ('Fontanero', 'Fontanero (G)'), ('Manitas', 'Manitas (G)'), ('Aire Acondicionado', 'Aire Acondicionado (G)'), ('Electrodomésticos', 'Electrodomésticos (G)'), ('Calderas', 'Calderas (G)'), ('Persianista', 'Persianista (G)'), ('Albañil', 'Albañil (G)'), ('Gastos venta inmueble', 'Gastos venta inmueble'), ('Otro', 'Otro')], max_length=30, verbose_name='Servicios & Gastos'),
        ),
        migrations.CreateModel(
            name='Contratoalquilerdeducciones',
            fields=[
                ('id_contrato_deducciones', models.AutoField(primary_key=True, serialize=False)),
                ('servicios_pago_inquilinos', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='N', max_length=2, verbose_name='Corresponde al inquilino')),
                ('fk_Contratoalquilerdeducciones_Propiedadcontratoalquiler', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.propiedadcontratoalquiler', verbose_name='Contrato de Alquiler de la Propiedad')),
                ('fk_Contratoalquilerdeducciones_Propiedadeducciones', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.propiedadeducciones', verbose_name='Deducciones que abona la propiedad')),
            ],
            options={
                'verbose_name': 'Deducciones del Contrato de Alquiler',
                'db_table': 'DEDUCCIONES CONTRATO ALQUILER',
                'ordering': ['fk_Contratoalquilerdeducciones_Propiedadcontratoalquiler', 'fk_Contratoalquilerdeducciones_Propiedadeducciones'],
            },
        ),
    ]
