# Generated by Django 3.2.19 on 2023-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0006_auto_20230620_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoalquilerdeducciones',
            options={'ordering': ['fk_Contratoalquilerdeducciones_Propiedadcontratoalquiler', 'servicios_pago_inquilinos'], 'verbose_name': 'Deducciones del Contrato de Alquiler'},
        ),
        migrations.AlterModelOptions(
            name='propiedadcontratoalquiler',
            options={'verbose_name': 'Contrato de Alquiler de la Propiedad'},
        ),
        migrations.AlterModelOptions(
            name='propiedadeducciones',
            options={'ordering': ['fk_Propiedadeducciones_Propiedades', 'servicios_pago_propiedad'], 'verbose_name': 'Deducciones de la Propiedad'},
        ),
        migrations.AlterField(
            model_name='propiedadeducciones',
            name='servicios_pago_propiedad',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Corresponde a la propiedad'),
        ),
    ]
