# Generated by Django 3.2.19 on 2023-06-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0007_auto_20230621_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudacontratoalquiler',
            fields=[
                ('id_deuda_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_origen_deuda_alquiler', models.DateField(verbose_name='Fecha de origen de la deuda')),
                ('monto_deuda_alquiler', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto original de la deuda')),
                ('fk_Deudacontratoalquiler_Propiedadcontratoalquiler', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.propiedadcontratoalquiler', verbose_name='Contrato de alquiler que contrae deuda')),
            ],
            options={
                'verbose_name': 'Deuda contraída por el arrendatario',
                'db_table': 'DEUDA CONTRAÍDA POR EL ARRENDATARIO',
                'ordering': ['fk_Deudacontratoalquiler_Propiedadcontratoalquiler', 'fecha_origen_deuda_alquiler'],
            },
        ),
        migrations.CreateModel(
            name='Cancelaciondeudacontratoalquiler',
            fields=[
                ('id_cancelacion_deuda_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cancelacion_deuda_alquiler', models.DateField(verbose_name='Fecha de cancelación de deuda')),
                ('monto_cancelacion_deuda_alquiler', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de cancelación de deuda')),
                ('fk_Cancelaciondeudacontratoalquiler_Deudacontratoalquiler', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.deudacontratoalquiler', verbose_name='Cancelación de deuda del contrato de alquiler')),
            ],
        ),
    ]
