# Generated by Django 3.2.19 on 2023-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0008_cancelaciondeudacontratoalquiler_deudacontratoalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='aumentos_indice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Índice de aumento'),
        ),
    ]
