# Generated by Django 3.2.19 on 2023-06-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0010_auto_20230624_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='fk_Propiedadcontratoaumentos_Propiedadcontratoalquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='propiedadcontratoaumentos_set', to='appMEGA.propiedadcontratoalquiler', verbose_name='Contrato de alquiler'),
        ),
    ]
