# Generated by Django 3.2.19 on 2023-06-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0011_alter_propiedadcontratoaumentos_fk_propiedadcontratoaumentos_propiedadcontratoalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelaciondeudacontratoalquiler',
            name='fk_Cancelaciondeudacontratoalquiler_Deudacontratoalquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cancelaciondeudacontratoalquiler_set', to='appMEGA.deudacontratoalquiler', verbose_name='Cancelación de deuda del contrato de alquiler'),
        ),
        migrations.AlterField(
            model_name='deudacontratoalquiler',
            name='fk_Deudacontratoalquiler_Propiedadcontratoalquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deudacontratoalquiler_set', to='appMEGA.propiedadcontratoalquiler', verbose_name='Contrato de alquiler que contrae deuda'),
        ),
    ]
