# Generated by Django 3.2.19 on 2023-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0012_auto_20230624_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelaciondeudacontratoalquiler',
            name='cancelacion_observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
    ]
