# Generated by Django 3.2.19 on 2023-06-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0014_auto_20230625_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsliquidacion',
            name='fk_Itemsliquidacion_Liquidacionencabezado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.liquidacionencabezado', verbose_name='Encabezado de liquidación'),
        ),
    ]
