# Generated by Django 3.2.19 on 2023-06-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0016_auto_20230625_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidaciondetalle',
            name='fk_Liquidaciondetalle_Itemsliquidacion',
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='fk_Liquidaciondetalle_Tipodeduccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='appMEGA.tipodeduccion', verbose_name='Detalles de liquidación'),
        ),
        migrations.AlterField(
            model_name='tipodeduccion',
            name='tipo_deduccion_categoria',
            field=models.CharField(choices=[('S', 'Servicio'), ('G', 'Gasto'), ('B', 'Alquiler-Base'), ('I', 'Ingreso por venta'), ('0', '------------------')], default='0', max_length=25, verbose_name='Categoría deducción'),
        ),
        migrations.AlterField(
            model_name='tipodeduccion',
            name='tipo_deduccion_descripcion',
            field=models.CharField(choices=[('RSU', 'RSU (S)'), ('IBI', 'IBI (G)'), ('Comunidad', 'Comunidad (G)'), ('Seguro del hogar', 'Seguro del hogar (G)'), ('Luz', 'Luz (S)'), ('Agua', 'Agua (S)'), ('Gas', 'Gas (S)'), ('Internet', 'Internet (S)'), ('Electricista', 'Electricista (G)'), ('Calefacción', 'Calefacción (G)'), ('Fontanero', 'Fontanero (G)'), ('Manitas', 'Manitas (G)'), ('Aire Acondicionado', 'Aire Acondicionado (G)'), ('Electrodomésticos', 'Electrodomésticos (G)'), ('Calderas', 'Calderas (G)'), ('Persianista', 'Persianista (G)'), ('Albañil', 'Albañil (G)'), ('Gastos venta inmueble', 'Gastos venta inmueble'), ('Renta', 'Renta (B)'), ('Deuda pendiente', 'Deuda pendiente(B)'), ('Garantía', 'Garantía(B)'), ('Fianza', 'Fianza (B)'), ('Otro', 'Otro')], default='0', max_length=30, verbose_name='Concepto deducción'),
        ),
        migrations.DeleteModel(
            name='Itemsliquidacion',
        ),
    ]
