# Generated by Django 3.2.19 on 2023-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0018_alter_tipodoc_tipo_doc_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadcontratoaumentos',
            name='diferencia_fianza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia en la fianza'),
        ),
    ]
