# Generated by Django 3.2.19 on 2023-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0021_auto_20230718_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelaciondeudacontratoalquiler',
            name='deudapendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda pendiente'),
        ),
    ]
