# Generated by Django 3.2.19 on 2023-07-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0022_cancelaciondeudacontratoalquiler_deudapendiente'),
    ]

    operations = [
    ]
