# Generated by Django 3.2.19 on 2023-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0023_auto_20230719_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelaciondeudacontratoalquiler',
            name='deudapendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Deuda pendiente'),
        ),
    ]
