# Generated by Django 3.2.19 on 2023-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0024_alter_cancelaciondeudacontratoalquiler_deudapendiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidaciondetalle',
            options={'ordering': ['detalle_liquidacion_monto'], 'verbose_name': 'Detalle de items liquidados'},
        ),
        migrations.RemoveField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_importe',
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_debe',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Debe item liquidado'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_irpf',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='IRPF item liquidado'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_iva',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='IVA item liquidado'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Monto item liquidado'),
        ),
        migrations.AlterField(
            model_name='comprobantedetalle',
            name='comprobante_detalle_irpf',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='irpf'),
        ),
        migrations.AlterField(
            model_name='comprobantedetalle',
            name='comprobante_detalle_iva',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='IVA'),
        ),
    ]
