# Generated by Django 3.2.19 on 2023-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0025_auto_20230816_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_debe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Debe item liquidado'),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_irpf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IRPF item liquidado'),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='detalle_liquidacion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA item liquidado'),
        ),
    ]
