# Generated by Django 3.2.19 on 2023-09-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0027_alter_tipodeduccion_tipo_deduccion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cl_estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('Sin especificar', 'Sin especificar')], default='ACTIVO', max_length=20, verbose_name='Estado del cliente'),
        ),
    ]
