# Generated by Django 3.2.19 on 2023-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMEGA', '0028_alter_clientes_cl_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadcontratoaumentos',
            name='aumento_mes_mismo',
            field=models.IntegerField(default=1, verbose_name='Aumento en el mes siguiente'),
        ),
    ]
